(* generated by Ott 0.30 from: smt_lang.ott *)

type u32 = string
type u64 = string

type 
exp = 
   Var of u32
 | Bits
 | Bits64 of u64 * u32
 | Bool
 | Eq of exp * exp
 | Neq of exp * exp
 | And of exp * exp
 | Or of exp * exp
 | Not of exp
 | Bvnot of exp
 | Bvredand of exp
 | Bvredor of exp
 | Bvand of exp * exp
 | Bvor of exp * exp
 | Bvxor of exp * exp
 | Bvnand of exp * exp
 | Bvnor of exp * exp
 | Bvxnor of exp * exp
 | Bvneg of exp
 | Bvadd of exp * exp
 | Bvsub of exp * exp
 | Bvmul of exp * exp
 | Bvudiv of exp * exp
 | Bvsdiv of exp * exp
 | Bvurem of exp * exp
 | Bvsrem of exp * exp
 | Bvsmod of exp * exp
 | Bvult of exp * exp
 | Bvslt of exp * exp
 | Bvule of exp * exp
 | Bvsle of exp * exp
 | Bvuge of exp * exp
 | Bvsge of exp * exp
 | Bvugt of exp * exp
 | Bvsgt of exp * exp
 | Extract of u32 * u32 * exp
 | ZeroExtend of u32 * exp
 | SignExtend of u32 * exp
 | Bvshl of exp * exp
 | Bvlshr of exp * exp
 | Bvashr of exp * exp
 | Concat of exp * exp
 | Ite of exp * exp * exp


type 
ty = 
   Ty_Bool
 | Ty_BitVec of u32



